# Generated by Django 4.2.11 on 2024-03-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_postimages_image_alter_postimages_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimages",
            name="image",
            field=models.ImageField(upload_to="posts/"),
        ),
    ]
