# Generated by Django 4.2.11 on 2024-03-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="Quantity", new_name="quantity",
        ),
    ]
